version: '2.1'

services:
  redis:
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    container_name: redis
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    restart: always
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - ./conf:/usr/local/etc/redis/

