version: '2'

services:
  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
    ports:
      - '${REDIS_PORT}:6379'
    restart: always
